# =====================================================
# DECOMPILED FROM .pyc FILE
# This is a PARTIAL reconstruction from bytecode
# Some parts may be incomplete or inaccurate
# =====================================================

# IMPORTS
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
import re
import os
from datetime import datetime, timedelta
from webdriver_manager.chrome import ChromeDriverManager
import shutil
import random
from urllib.parse import urlparse
import pandas as pd
import csv
import numpy as np
import warnings
from IPython.display import display, HTML

# =====================================================
# BYTECODE DISASSEMBLY
# =====================================================

Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=0, starts_line=8, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=1, argval=None, argrepr='None', offset=2, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=0, argval='time', argrepr='time', offset=4, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=0, argval='time', argrepr='time', offset=6, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=8, starts_line=9, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=2, argval=('webdriver',), argrepr="('webdriver',)", offset=10, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=1, argval='selenium', argrepr='selenium', offset=12, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_FROM', opcode=109, arg=2, argval='webdriver', argrepr='webdriver', offset=14, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=2, argval='webdriver', argrepr='webdriver', offset=16, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=18, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=20, starts_line=10, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=3, argval=('By',), argrepr="('By',)", offset=22, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=3, argval='selenium.webdriver.common.by', argrepr='selenium.webdriver.common.by', offset=24, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_FROM', opcode=109, arg=4, argval='By', argrepr='By', offset=26, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=4, argval='By', argrepr='By', offset=28, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=30, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=32, starts_line=11, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=4, argval=('WebDriverWait',), argrepr="('WebDriverWait',)", offset=34, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=5, argval='selenium.webdriver.support.ui', argrepr='selenium.webdriver.support.ui', offset=36, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_FROM', opcode=109, arg=6, argval='WebDriverWait', argrepr='WebDriverWait', offset=38, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=6, argval='WebDriverWait', argrepr='WebDriverWait', offset=40, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=42, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=44, starts_line=12, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=5, argval=('expected_conditions',), argrepr="('expected_conditions',)", offset=46, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=7, argval='selenium.webdriver.support', argrepr='selenium.webdriver.support', offset=48, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_FROM', opcode=109, arg=8, argval='expected_conditions', argrepr='expected_conditions', offset=50, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=9, argval='EC', argrepr='EC', offset=52, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=54, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=56, starts_line=13, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=6, argval=('Keys',), argrepr="('Keys',)", offset=58, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=10, argval='selenium.webdriver.common.keys', argrepr='selenium.webdriver.common.keys', offset=60, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_FROM', opcode=109, arg=11, argval='Keys', argrepr='Keys', offset=62, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=11, argval='Keys', argrepr='Keys', offset=64, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=66, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=68, starts_line=14, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=1, argval=None, argrepr='None', offset=70, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=12, argval='re', argrepr='re', offset=72, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=12, argval='re', argrepr='re', offset=74, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=76, starts_line=15, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=1, argval=None, argrepr='None', offset=78, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=13, argval='os', argrepr='os', offset=80, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=13, argval='os', argrepr='os', offset=82, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=84, starts_line=17, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=7, argval=('datetime',), argrepr="('datetime',)", offset=86, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=14, argval='datetime', argrepr='datetime', offset=88, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_FROM', opcode=109, arg=14, argval='datetime', argrepr='datetime', offset=90, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=15, argval='dt', argrepr='dt', offset=92, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=94, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=96, starts_line=18, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=8, argval=('timedelta',), argrepr="('timedelta',)", offset=98, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=14, argval='datetime', argrepr='datetime', offset=100, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_FROM', opcode=109, arg=16, argval='timedelta', argrepr='timedelta', offset=102, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=16, argval='timedelta', argrepr='timedelta', offset=104, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=106, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=108, starts_line=19, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=9, argval=('sleep',), argrepr="('sleep',)", offset=110, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=0, argval='time', argrepr='time', offset=112, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_FROM', opcode=109, arg=17, argval='sleep', argrepr='sleep', offset=114, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=17, argval='sleep', argrepr='sleep', offset=116, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=118, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=120, starts_line=20, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=2, argval=('webdriver',), argrepr="('webdriver',)", offset=122, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=1, argval='selenium', argrepr='selenium', offset=124, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_FROM', opcode=109, arg=2, argval='webdriver', argrepr='webdriver', offset=126, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=2, argval='webdriver', argrepr='webdriver', offset=128, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=130, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=132, starts_line=21, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=6, argval=('Keys',), argrepr="('Keys',)", offset=134, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=10, argval='selenium.webdriver.common.keys', argrepr='selenium.webdriver.common.keys', offset=136, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_FROM', opcode=109, arg=11, argval='Keys', argrepr='Keys', offset=138, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=11, argval='Keys', argrepr='Keys', offset=140, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=142, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=144, starts_line=22, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=10, argval=('ChromeDriverManager',), argrepr="('ChromeDriverManager',)", offset=146, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=18, argval='webdriver_manager.chrome', argrepr='webdriver_manager.chrome', offset=148, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_FROM', opcode=109, arg=19, argval='ChromeDriverManager', argrepr='ChromeDriverManager', offset=150, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=19, argval='ChromeDriverManager', argrepr='ChromeDriverManager', offset=152, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=154, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=156, starts_line=23, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=1, argval=None, argrepr='None', offset=158, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=20, argval='shutil', argrepr='shutil', offset=160, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=20, argval='shutil', argrepr='shutil', offset=162, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=164, starts_line=24, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=1, argval=None, argrepr='None', offset=166, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=21, argval='os.path', argrepr='os.path', offset=168, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=13, argval='os', argrepr='os', offset=170, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=172, starts_line=25, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=1, argval=None, argrepr='None', offset=174, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=22, argval='random', argrepr='random', offset=176, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=22, argval='random', argrepr='random', offset=178, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=180, starts_line=26, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=1, argval=None, argrepr='None', offset=182, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=23, argval='urllib.parse', argrepr='urllib.parse', offset=184, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_FROM', opcode=109, arg=24, argval='parse', argrepr='parse', offset=186, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=25, argval='urlparse', argrepr='urlparse', offset=188, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=190, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=192, starts_line=28, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=1, argval=None, argrepr='None', offset=194, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=26, argval='pandas', argrepr='pandas', offset=196, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=27, argval='pd', argrepr='pd', offset=198, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=200, starts_line=29, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=1, argval=None, argrepr='None', offset=202, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=28, argval='csv', argrepr='csv', offset=204, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=28, argval='csv', argrepr='csv', offset=206, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=208, starts_line=30, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=1, argval=None, argrepr='None', offset=210, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=29, argval='numpy', argrepr='numpy', offset=212, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=30, argval='np', argrepr='np', offset=214, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=216, starts_line=32, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=1, argval=None, argrepr='None', offset=218, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=31, argval='warnings', argrepr='warnings', offset=220, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=31, argval='warnings', argrepr='warnings', offset=222, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=31, argval='warnings', argrepr='warnings', offset=224, starts_line=33, is_jump_target=False)
Instruction(opname='LOAD_METHOD', opcode=160, arg=32, argval='filterwarnings', argrepr='filterwarnings', offset=226, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=11, argval='ignore', argrepr="'ignore'", offset=228, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=1, argval=1, argrepr='', offset=230, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=232, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=234, starts_line=39, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=12, argval=('display', 'HTML'), argrepr="('display', 'HTML')", offset=236, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_NAME', opcode=108, arg=33, argval='IPython.display', argrepr='IPython.display', offset=238, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_FROM', opcode=109, arg=34, argval='display', argrepr='display', offset=240, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=34, argval='display', argrepr='display', offset=242, starts_line=None, is_jump_target=False)
Instruction(opname='IMPORT_FROM', opcode=109, arg=35, argval='HTML', argrepr='HTML', offset=244, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=35, argval='HTML', argrepr='HTML', offset=246, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=248, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=34, argval='display', argrepr='display', offset=250, starts_line=40, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=35, argval='HTML', argrepr='HTML', offset=252, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=13, argval='<style>.container { width:90% !important; }</style>', argrepr="'<style>.container { width:90% !important; }</style>'", offset=254, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION', opcode=131, arg=1, argval=1, argrepr='', offset=256, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION', opcode=131, arg=1, argval=1, argrepr='', offset=258, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=260, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=15, argval='dt', argrepr='dt', offset=262, starts_line=46, is_jump_target=False)
Instruction(opname='LOAD_METHOD', opcode=160, arg=36, argval='today', argrepr='today', offset=264, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=0, argval=0, argrepr='', offset=266, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=36, argval='today', argrepr='today', offset=268, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=36, argval='today', argrepr='today', offset=270, starts_line=47, is_jump_target=False)
Instruction(opname='LOAD_METHOD', opcode=160, arg=37, argval='strftime', argrepr='strftime', offset=272, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=14, argval='%d-%m-%Y', argrepr="'%d-%m-%Y'", offset=274, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=1, argval=1, argrepr='', offset=276, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=38, argval='ngay_du_lieu', argrepr='ngay_du_lieu', offset=278, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=15, argval='Tham chiếu/', argrepr="'Tham chiếu/'", offset=280, starts_line=55, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=39, argval='map_path', argrepr='map_path', offset=282, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=27, argval='pd', argrepr='pd', offset=284, starts_line=56, is_jump_target=False)
Instruction(opname='LOAD_ATTR', opcode=106, arg=40, argval='read_excel', argrepr='read_excel', offset=286, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=39, argval='map_path', argrepr='map_path', offset=288, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=16, argval='\\MapnganhKT_theo nganh SBV TPBank_Cap04.xlsx', argrepr="'\\\\MapnganhKT_theo nganh SBV TPBank_Cap04.xlsx'", offset=290, starts_line=None, is_jump_target=False)
Instruction(opname='BINARY_ADD', opcode=23, arg=None, argval=None, argrepr='', offset=292, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=17, argval='str', argrepr="'str'", offset=294, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=18, argval=('dtype',), argrepr="('dtype',)", offset=296, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION_KW', opcode=141, arg=2, argval=2, argrepr='', offset=298, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=41, argval='map_data_segment', argrepr='map_data_segment', offset=300, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=19, argval='Input\\Chưa xử lý', argrepr="'Input\\\\Chưa xử lý'", offset=302, starts_line=62, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=42, argval='path', argrepr='path', offset=304, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=20, argval='Input\\Đã xử lý', argrepr="'Input\\\\Đã xử lý'", offset=306, starts_line=63, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=43, argval='copy_path', argrepr='copy_path', offset=308, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=13, argval='os', argrepr='os', offset=310, starts_line=64, is_jump_target=False)
Instruction(opname='LOAD_METHOD', opcode=160, arg=44, argval='listdir', argrepr='listdir', offset=312, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=42, argval='path', argrepr='path', offset=314, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=1, argval=1, argrepr='', offset=316, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=45, argval='file_list', argrepr='file_list', offset=318, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=21, argval=<code object <listcomp> at 0x000002C9792C56E0, file "mst_com.py", line 65>, argrepr='<code object <listcomp> at 0x000002C9792C56E0, file "mst_com.py", line 65>', offset=320, starts_line=65, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=22, argval='<listcomp>', argrepr="'<listcomp>'", offset=322, starts_line=None, is_jump_target=False)
Instruction(opname='MAKE_FUNCTION', opcode=132, arg=0, argval=0, argrepr='', offset=324, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=45, argval='file_list', argrepr='file_list', offset=326, starts_line=None, is_jump_target=False)
Instruction(opname='GET_ITER', opcode=68, arg=None, argval=None, argrepr='', offset=328, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION', opcode=131, arg=1, argval=1, argrepr='', offset=330, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=45, argval='file_list', argrepr='file_list', offset=332, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=45, argval='file_list', argrepr='file_list', offset=334, starts_line=71, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=336, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=46, argval='len', argrepr='len', offset=338, starts_line=77, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=45, argval='file_list', argrepr='file_list', offset=340, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION', opcode=131, arg=1, argval=1, argrepr='', offset=342, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=344, starts_line=None, is_jump_target=False)
Instruction(opname='COMPARE_OP', opcode=107, arg=4, argval='>', argrepr='>', offset=346, starts_line=None, is_jump_target=False)
Instruction(opname='POP_JUMP_IF_FALSE', opcode=114, arg=238, argval=476, argrepr='to 476', offset=348, starts_line=None, is_jump_target=False)
Instruction(opname='SETUP_FINALLY', opcode=122, arg=31, argval=414, argrepr='to 414', offset=350, starts_line=78, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=45, argval='file_list', argrepr='file_list', offset=352, starts_line=79, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=354, starts_line=None, is_jump_target=False)
Instruction(opname='BINARY_SUBSCR', opcode=25, arg=None, argval=None, argrepr='', offset=356, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=47, argval='filename', argrepr='filename', offset=358, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=27, argval='pd', argrepr='pd', offset=360, starts_line=80, is_jump_target=False)
Instruction(opname='LOAD_ATTR', opcode=106, arg=40, argval='read_excel', argrepr='read_excel', offset=362, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=42, argval='path', argrepr='path', offset=364, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=23, argval='\\', argrepr="'\\\\'", offset=366, starts_line=None, is_jump_target=False)
Instruction(opname='BINARY_ADD', opcode=23, arg=None, argval=None, argrepr='', offset=368, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=47, argval='filename', argrepr='filename', offset=370, starts_line=None, is_jump_target=False)
Instruction(opname='BINARY_ADD', opcode=23, arg=None, argval=None, argrepr='', offset=372, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=17, argval='str', argrepr="'str'", offset=374, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=18, argval=('dtype',), argrepr="('dtype',)", offset=376, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION_KW', opcode=141, arg=2, argval=2, argrepr='', offset=378, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=48, argval='data', argrepr='data', offset=380, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=24, argval='Mã số thuế', argrepr="'Mã số thuế'", offset=382, starts_line=82, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=48, argval='data', argrepr='data', offset=384, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_ATTR', opcode=106, arg=49, argval='columns', argrepr='columns', offset=386, starts_line=None, is_jump_target=False)
Instruction(opname='CONTAINS_OP', opcode=118, arg=0, argval=0, argrepr='', offset=388, starts_line=None, is_jump_target=False)
Instruction(opname='POP_JUMP_IF_FALSE', opcode=114, arg=201, argval=402, argrepr='to 402', offset=390, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=50, argval='print', argrepr='print', offset=392, starts_line=83, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=25, argval='Đang sử lý ================================', argrepr="'Đang sử lý ================================'", offset=394, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION', opcode=131, arg=1, argval=1, argrepr='', offset=396, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=398, starts_line=None, is_jump_target=False)
Instruction(opname='JUMP_FORWARD', opcode=110, arg=4, argval=410, argrepr='to 410', offset=400, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=50, argval='print', argrepr='print', offset=402, starts_line=85, is_jump_target=True)
Instruction(opname='LOAD_CONST', opcode=100, arg=26, argval='Không tìm thấy cột mã số thuế =============', argrepr="'Không tìm thấy cột mã số thuế ============='", offset=404, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION', opcode=131, arg=1, argval=1, argrepr='', offset=406, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=408, starts_line=None, is_jump_target=False)
Instruction(opname='POP_BLOCK', opcode=87, arg=None, argval=None, argrepr='', offset=410, starts_line=None, is_jump_target=True)
Instruction(opname='JUMP_FORWARD', opcode=110, arg=8, argval=430, argrepr='to 430', offset=412, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=414, starts_line=86, is_jump_target=True)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=416, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=418, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=50, argval='print', argrepr='print', offset=420, starts_line=87, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=27, argval='Xử lý file lỗi ==============================', argrepr="'Xử lý file lỗi =============================='", offset=422, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION', opcode=131, arg=1, argval=1, argrepr='', offset=424, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=426, starts_line=None, is_jump_target=False)
Instruction(opname='POP_EXCEPT', opcode=89, arg=None, argval=None, argrepr='', offset=428, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=20, argval='shutil', argrepr='shutil', offset=430, starts_line=89, is_jump_target=True)
Instruction(opname='LOAD_METHOD', opcode=160, arg=51, argval='copyfile', argrepr='copyfile', offset=432, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=42, argval='path', argrepr='path', offset=434, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=23, argval='\\', argrepr="'\\\\'", offset=436, starts_line=None, is_jump_target=False)
Instruction(opname='BINARY_ADD', opcode=23, arg=None, argval=None, argrepr='', offset=438, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=47, argval='filename', argrepr='filename', offset=440, starts_line=None, is_jump_target=False)
Instruction(opname='BINARY_ADD', opcode=23, arg=None, argval=None, argrepr='', offset=442, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=43, argval='copy_path', argrepr='copy_path', offset=444, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=23, argval='\\', argrepr="'\\\\'", offset=446, starts_line=None, is_jump_target=False)
Instruction(opname='BINARY_ADD', opcode=23, arg=None, argval=None, argrepr='', offset=448, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=47, argval='filename', argrepr='filename', offset=450, starts_line=None, is_jump_target=False)
Instruction(opname='BINARY_ADD', opcode=23, arg=None, argval=None, argrepr='', offset=452, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=2, argval=2, argrepr='', offset=454, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=456, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=13, argval='os', argrepr='os', offset=458, starts_line=90, is_jump_target=False)
Instruction(opname='LOAD_METHOD', opcode=160, arg=52, argval='remove', argrepr='remove', offset=460, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=42, argval='path', argrepr='path', offset=462, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=23, argval='\\', argrepr="'\\\\'", offset=464, starts_line=None, is_jump_target=False)
Instruction(opname='BINARY_ADD', opcode=23, arg=None, argval=None, argrepr='', offset=466, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=47, argval='filename', argrepr='filename', offset=468, starts_line=None, is_jump_target=False)
Instruction(opname='BINARY_ADD', opcode=23, arg=None, argval=None, argrepr='', offset=470, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=1, argval=1, argrepr='', offset=472, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=474, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=46, argval='len', argrepr='len', offset=476, starts_line=91, is_jump_target=True)
Instruction(opname='LOAD_NAME', opcode=101, arg=48, argval='data', argrepr='data', offset=478, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION', opcode=131, arg=1, argval=1, argrepr='', offset=480, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=482, starts_line=None, is_jump_target=False)
Instruction(opname='COMPARE_OP', opcode=107, arg=4, argval='>', argrepr='>', offset=484, starts_line=None, is_jump_target=False)
Instruction(opname='POP_JUMP_IF_FALSE', opcode=114, arg=248, argval=496, argrepr='to 496', offset=486, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=48, argval='data', argrepr='data', offset=488, starts_line=92, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=24, argval='Mã số thuế', argrepr="'Mã số thuế'", offset=490, starts_line=None, is_jump_target=False)
Instruction(opname='BINARY_SUBSCR', opcode=25, arg=None, argval=None, argrepr='', offset=492, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=53, argval='keys', argrepr='keys', offset=494, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=50, argval='print', argrepr='print', offset=496, starts_line=95, is_jump_target=True)
Instruction(opname='LOAD_CONST', opcode=100, arg=28, argval='Số mã số thuế: ', argrepr="'Số mã số thuế: '", offset=498, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=46, argval='len', argrepr='len', offset=500, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=53, argval='keys', argrepr='keys', offset=502, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION', opcode=131, arg=1, argval=1, argrepr='', offset=504, starts_line=None, is_jump_target=False)
Instruction(opname='FORMAT_VALUE', opcode=155, arg=0, argval=(None, False), argrepr='', offset=506, starts_line=None, is_jump_target=False)
Instruction(opname='BUILD_STRING', opcode=157, arg=2, argval=2, argrepr='', offset=508, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION', opcode=131, arg=1, argval=1, argrepr='', offset=510, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=512, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=2, argval='webdriver', argrepr='webdriver', offset=514, starts_line=138, is_jump_target=False)
Instruction(opname='LOAD_METHOD', opcode=160, arg=54, argval='Chrome', argrepr='Chrome', offset=516, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=0, argval=0, argrepr='', offset=518, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=55, argval='driver', argrepr='driver', offset=520, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=55, argval='driver', argrepr='driver', offset=522, starts_line=140, is_jump_target=False)
Instruction(opname='LOAD_METHOD', opcode=160, arg=56, argval='get', argrepr='get', offset=524, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=29, argval='https://www.masothue.com/', argrepr="'https://www.masothue.com/'", offset=526, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=1, argval=1, argrepr='', offset=528, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=530, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=17, argval='sleep', argrepr='sleep', offset=532, starts_line=141, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=30, argval=2, argrepr='2', offset=534, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION', opcode=131, arg=1, argval=1, argrepr='', offset=536, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=538, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=27, argval='pd', argrepr='pd', offset=540, starts_line=143, is_jump_target=False)
Instruction(opname='LOAD_METHOD', opcode=160, arg=57, argval='DataFrame', argrepr='DataFrame', offset=542, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=0, argval=0, argrepr='', offset=544, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=58, argval='dataframes', argrepr='dataframes', offset=546, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=53, argval='keys', argrepr='keys', offset=548, starts_line=145, is_jump_target=False)
Instruction(opname='GET_ITER', opcode=68, arg=None, argval=None, argrepr='', offset=550, starts_line=None, is_jump_target=False)
Instruction(opname='FOR_ITER', opcode=93, arg=190, argval=934, argrepr='to 934', offset=552, starts_line=None, is_jump_target=True)
Instruction(opname='STORE_NAME', opcode=90, arg=59, argval='key', argrepr='key', offset=554, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=50, argval='print', argrepr='print', offset=556, starts_line=146, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=59, argval='key', argrepr='key', offset=558, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION', opcode=131, arg=1, argval=1, argrepr='', offset=560, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=562, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=46, argval='len', argrepr='len', offset=564, starts_line=147, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=59, argval='key', argrepr='key', offset=566, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION', opcode=131, arg=1, argval=1, argrepr='', offset=568, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=31, argval=10, argrepr='10', offset=570, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=46, argval='len', argrepr='len', offset=572, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=59, argval='key', argrepr='key', offset=574, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION', opcode=131, arg=1, argval=1, argrepr='', offset=576, starts_line=None, is_jump_target=False)
Instruction(opname='BINARY_OR', opcode=66, arg=None, argval=None, argrepr='', offset=578, starts_line=None, is_jump_target=False)
Instruction(opname='DUP_TOP', opcode=4, arg=None, argval=None, argrepr='', offset=580, starts_line=None, is_jump_target=False)
Instruction(opname='ROT_THREE', opcode=3, arg=None, argval=None, argrepr='', offset=582, starts_line=None, is_jump_target=False)
Instruction(opname='COMPARE_OP', opcode=107, arg=3, argval='!=', argrepr='!=', offset=584, starts_line=None, is_jump_target=False)
Instruction(opname='EXTENDED_ARG', opcode=144, arg=1, argval=1, argrepr='', offset=586, starts_line=None, is_jump_target=False)
Instruction(opname='POP_JUMP_IF_FALSE', opcode=114, arg=300, argval=600, argrepr='to 600', offset=588, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=32, argval=14, argrepr='14', offset=590, starts_line=None, is_jump_target=False)
Instruction(opname='COMPARE_OP', opcode=107, arg=3, argval='!=', argrepr='!=', offset=592, starts_line=None, is_jump_target=False)
Instruction(opname='EXTENDED_ARG', opcode=144, arg=1, argval=1, argrepr='', offset=594, starts_line=None, is_jump_target=False)
Instruction(opname='POP_JUMP_IF_FALSE', opcode=114, arg=312, argval=624, argrepr='to 624', offset=596, starts_line=None, is_jump_target=False)
Instruction(opname='JUMP_FORWARD', opcode=110, arg=2, argval=604, argrepr='to 604', offset=598, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=600, starts_line=None, is_jump_target=True)
Instruction(opname='JUMP_FORWARD', opcode=110, arg=10, argval=624, argrepr='to 624', offset=602, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=50, argval='print', argrepr='print', offset=604, starts_line=148, is_jump_target=True)
Instruction(opname='LOAD_CONST', opcode=100, arg=28, argval='Số mã số thuế: ', argrepr="'Số mã số thuế: '", offset=606, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=53, argval='keys', argrepr='keys', offset=608, starts_line=None, is_jump_target=False)
Instruction(opname='FORMAT_VALUE', opcode=155, arg=0, argval=(None, False), argrepr='', offset=610, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=33, argval=' sai định dạng', argrepr="' sai định dạng'", offset=612, starts_line=None, is_jump_target=False)
Instruction(opname='BUILD_STRING', opcode=157, arg=3, argval=3, argrepr='', offset=614, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION', opcode=131, arg=1, argval=1, argrepr='', offset=616, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=618, starts_line=None, is_jump_target=False)
Instruction(opname='EXTENDED_ARG', opcode=144, arg=1, argval=1, argrepr='', offset=620, starts_line=None, is_jump_target=False)
Instruction(opname='JUMP_ABSOLUTE', opcode=113, arg=276, argval=552, argrepr='to 552', offset=622, starts_line=None, is_jump_target=False)
Instruction(opname='SETUP_FINALLY', opcode=122, arg=143, argval=912, argrepr='to 912', offset=624, starts_line=150, is_jump_target=True)
Instruction(opname='LOAD_NAME', opcode=101, arg=55, argval='driver', argrepr='driver', offset=626, starts_line=151, is_jump_target=False)
Instruction(opname='LOAD_METHOD', opcode=160, arg=60, argval='find_element', argrepr='find_element', offset=628, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=4, argval='By', argrepr='By', offset=630, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_ATTR', opcode=106, arg=61, argval='CLASS_NAME', argrepr='CLASS_NAME', offset=632, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=34, argval='input-group', argrepr="'input-group'", offset=634, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=2, argval=2, argrepr='', offset=636, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=62, argval='search_group', argrepr='search_group', offset=638, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=62, argval='search_group', argrepr='search_group', offset=640, starts_line=152, is_jump_target=False)
Instruction(opname='LOAD_METHOD', opcode=160, arg=60, argval='find_element', argrepr='find_element', offset=642, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=4, argval='By', argrepr='By', offset=644, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_ATTR', opcode=106, arg=63, argval='NAME', argrepr='NAME', offset=646, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=35, argval='q', argrepr="'q'", offset=648, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=2, argval=2, argrepr='', offset=650, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=64, argval='search', argrepr='search', offset=652, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=64, argval='search', argrepr='search', offset=654, starts_line=153, is_jump_target=False)
Instruction(opname='LOAD_METHOD', opcode=160, arg=65, argval='clear', argrepr='clear', offset=656, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=0, argval=0, argrepr='', offset=658, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=660, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=64, argval='search', argrepr='search', offset=662, starts_line=154, is_jump_target=False)
Instruction(opname='LOAD_METHOD', opcode=160, arg=66, argval='send_keys', argrepr='send_keys', offset=664, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=59, argval='key', argrepr='key', offset=666, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=1, argval=1, argrepr='', offset=668, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=670, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=17, argval='sleep', argrepr='sleep', offset=672, starts_line=155, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=36, argval=3, argrepr='3', offset=674, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION', opcode=131, arg=1, argval=1, argrepr='', offset=676, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=678, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=55, argval='driver', argrepr='driver', offset=680, starts_line=157, is_jump_target=False)
Instruction(opname='LOAD_METHOD', opcode=160, arg=67, argval='find_elements', argrepr='find_elements', offset=682, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=4, argval='By', argrepr='By', offset=684, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_ATTR', opcode=106, arg=68, argval='XPATH', argrepr='XPATH', offset=686, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=37, argval='//table[@class="table-taxinfo"]/tbody/tr', argrepr='\'//table[@class="table-taxinfo"]/tbody/tr\'', offset=688, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=2, argval=2, argrepr='', offset=690, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=69, argval='table_taxinfo', argrepr='table_taxinfo', offset=692, starts_line=None, is_jump_target=False)
Instruction(opname='BUILD_MAP', opcode=105, arg=0, argval=0, argrepr='', offset=694, starts_line=159, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=70, argval='value_dict', argrepr='value_dict', offset=696, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=69, argval='table_taxinfo', argrepr='table_taxinfo', offset=698, starts_line=160, is_jump_target=False)
Instruction(opname='GET_ITER', opcode=68, arg=None, argval=None, argrepr='', offset=700, starts_line=None, is_jump_target=False)
Instruction(opname='FOR_ITER', opcode=93, arg=35, argval=774, argrepr='to 774', offset=702, starts_line=None, is_jump_target=True)
Instruction(opname='STORE_NAME', opcode=90, arg=71, argval='row', argrepr='row', offset=704, starts_line=None, is_jump_target=False)
Instruction(opname='SETUP_FINALLY', opcode=122, arg=27, argval=762, argrepr='to 762', offset=706, starts_line=161, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=71, argval='row', argrepr='row', offset=708, starts_line=162, is_jump_target=False)
Instruction(opname='LOAD_METHOD', opcode=160, arg=67, argval='find_elements', argrepr='find_elements', offset=710, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=4, argval='By', argrepr='By', offset=712, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_ATTR', opcode=106, arg=72, argval='TAG_NAME', argrepr='TAG_NAME', offset=714, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=38, argval='td', argrepr="'td'", offset=716, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=2, argval=2, argrepr='', offset=718, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=720, starts_line=None, is_jump_target=False)
Instruction(opname='BINARY_SUBSCR', opcode=25, arg=None, argval=None, argrepr='', offset=722, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_ATTR', opcode=106, arg=73, argval='text', argrepr='text', offset=724, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=74, argval='key_info', argrepr='key_info', offset=726, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=71, argval='row', argrepr='row', offset=728, starts_line=163, is_jump_target=False)
Instruction(opname='LOAD_METHOD', opcode=160, arg=67, argval='find_elements', argrepr='find_elements', offset=730, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=4, argval='By', argrepr='By', offset=732, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_ATTR', opcode=106, arg=72, argval='TAG_NAME', argrepr='TAG_NAME', offset=734, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=38, argval='td', argrepr="'td'", offset=736, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=2, argval=2, argrepr='', offset=738, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=39, argval=1, argrepr='1', offset=740, starts_line=None, is_jump_target=False)
Instruction(opname='BINARY_SUBSCR', opcode=25, arg=None, argval=None, argrepr='', offset=742, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_ATTR', opcode=106, arg=73, argval='text', argrepr='text', offset=744, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=75, argval='value', argrepr='value', offset=746, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=75, argval='value', argrepr='value', offset=748, starts_line=164, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=70, argval='value_dict', argrepr='value_dict', offset=750, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=74, argval='key_info', argrepr='key_info', offset=752, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_SUBSCR', opcode=60, arg=None, argval=None, argrepr='', offset=754, starts_line=None, is_jump_target=False)
Instruction(opname='POP_BLOCK', opcode=87, arg=None, argval=None, argrepr='', offset=756, starts_line=None, is_jump_target=False)
Instruction(opname='EXTENDED_ARG', opcode=144, arg=1, argval=1, argrepr='', offset=758, starts_line=None, is_jump_target=False)
Instruction(opname='JUMP_ABSOLUTE', opcode=113, arg=351, argval=702, argrepr='to 702', offset=760, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=762, starts_line=165, is_jump_target=True)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=764, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=766, starts_line=None, is_jump_target=False)
Instruction(opname='POP_EXCEPT', opcode=89, arg=None, argval=None, argrepr='', offset=768, starts_line=166, is_jump_target=False)
Instruction(opname='EXTENDED_ARG', opcode=144, arg=1, argval=1, argrepr='', offset=770, starts_line=None, is_jump_target=False)
Instruction(opname='JUMP_ABSOLUTE', opcode=113, arg=351, argval=702, argrepr='to 702', offset=772, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=55, argval='driver', argrepr='driver', offset=774, starts_line=168, is_jump_target=True)
Instruction(opname='LOAD_METHOD', opcode=160, arg=67, argval='find_elements', argrepr='find_elements', offset=776, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=4, argval='By', argrepr='By', offset=778, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_ATTR', opcode=106, arg=68, argval='XPATH', argrepr='XPATH', offset=780, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=40, argval='//table[@class="table"]/tbody/tr', argrepr='\'//table[@class="table"]/tbody/tr\'', offset=782, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=2, argval=2, argrepr='', offset=784, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=76, argval='table_branch', argrepr='table_branch', offset=786, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=76, argval='table_branch', argrepr='table_branch', offset=788, starts_line=170, is_jump_target=False)
Instruction(opname='GET_ITER', opcode=68, arg=None, argval=None, argrepr='', offset=790, starts_line=None, is_jump_target=False)
Instruction(opname='FOR_ITER', opcode=93, arg=39, argval=872, argrepr='to 872', offset=792, starts_line=None, is_jump_target=True)
Instruction(opname='STORE_NAME', opcode=90, arg=71, argval='row', argrepr='row', offset=794, starts_line=None, is_jump_target=False)
Instruction(opname='SETUP_FINALLY', opcode=122, arg=31, argval=860, argrepr='to 860', offset=796, starts_line=171, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=71, argval='row', argrepr='row', offset=798, starts_line=172, is_jump_target=False)
Instruction(opname='LOAD_METHOD', opcode=160, arg=67, argval='find_elements', argrepr='find_elements', offset=800, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=4, argval='By', argrepr='By', offset=802, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_ATTR', opcode=106, arg=68, argval='XPATH', argrepr='XPATH', offset=804, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=41, argval='//td/strong', argrepr="'//td/strong'", offset=806, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=2, argval=2, argrepr='', offset=808, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=39, argval=1, argrepr='1', offset=810, starts_line=None, is_jump_target=False)
Instruction(opname='BINARY_SUBSCR', opcode=25, arg=None, argval=None, argrepr='', offset=812, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_ATTR', opcode=106, arg=73, argval='text', argrepr='text', offset=814, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=77, argval='ma', argrepr='ma', offset=816, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=71, argval='row', argrepr='row', offset=818, starts_line=173, is_jump_target=False)
Instruction(opname='LOAD_METHOD', opcode=160, arg=67, argval='find_elements', argrepr='find_elements', offset=820, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=4, argval='By', argrepr='By', offset=822, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_ATTR', opcode=106, arg=68, argval='XPATH', argrepr='XPATH', offset=824, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=41, argval='//td/strong', argrepr="'//td/strong'", offset=826, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=2, argval=2, argrepr='', offset=828, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=30, argval=2, argrepr='2', offset=830, starts_line=None, is_jump_target=False)
Instruction(opname='BINARY_SUBSCR', opcode=25, arg=None, argval=None, argrepr='', offset=832, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_ATTR', opcode=106, arg=73, argval='text', argrepr='text', offset=834, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=78, argval='nganh', argrepr='nganh', offset=836, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=77, argval='ma', argrepr='ma', offset=838, starts_line=174, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=70, argval='value_dict', argrepr='value_dict', offset=840, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=42, argval='Mã ngành nghề', argrepr="'Mã ngành nghề'", offset=842, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_SUBSCR', opcode=60, arg=None, argval=None, argrepr='', offset=844, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=78, argval='nganh', argrepr='nganh', offset=846, starts_line=175, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=70, argval='value_dict', argrepr='value_dict', offset=848, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=43, argval='Tên ngành nghề', argrepr="'Tên ngành nghề'", offset=850, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_SUBSCR', opcode=60, arg=None, argval=None, argrepr='', offset=852, starts_line=None, is_jump_target=False)
Instruction(opname='POP_BLOCK', opcode=87, arg=None, argval=None, argrepr='', offset=854, starts_line=None, is_jump_target=False)
Instruction(opname='EXTENDED_ARG', opcode=144, arg=1, argval=1, argrepr='', offset=856, starts_line=None, is_jump_target=False)
Instruction(opname='JUMP_ABSOLUTE', opcode=113, arg=396, argval=792, argrepr='to 792', offset=858, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=860, starts_line=181, is_jump_target=True)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=862, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=864, starts_line=None, is_jump_target=False)
Instruction(opname='POP_EXCEPT', opcode=89, arg=None, argval=None, argrepr='', offset=866, starts_line=182, is_jump_target=False)
Instruction(opname='EXTENDED_ARG', opcode=144, arg=1, argval=1, argrepr='', offset=868, starts_line=None, is_jump_target=False)
Instruction(opname='JUMP_ABSOLUTE', opcode=113, arg=396, argval=792, argrepr='to 792', offset=870, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=27, argval='pd', argrepr='pd', offset=872, starts_line=184, is_jump_target=True)
Instruction(opname='LOAD_ATTR', opcode=106, arg=79, argval='concat', argrepr='concat', offset=874, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=58, argval='dataframes', argrepr='dataframes', offset=876, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=27, argval='pd', argrepr='pd', offset=878, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_METHOD', opcode=160, arg=57, argval='DataFrame', argrepr='DataFrame', offset=880, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=70, argval='value_dict', argrepr='value_dict', offset=882, starts_line=None, is_jump_target=False)
Instruction(opname='BUILD_LIST', opcode=103, arg=1, argval=1, argrepr='', offset=884, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=1, argval=1, argrepr='', offset=886, starts_line=None, is_jump_target=False)
Instruction(opname='BUILD_LIST', opcode=103, arg=2, argval=2, argrepr='', offset=888, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=0, argval=0, argrepr='0', offset=890, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=44, argval=('axis',), argrepr="('axis',)", offset=892, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION_KW', opcode=141, arg=2, argval=2, argrepr='', offset=894, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_ATTR', opcode=106, arg=80, argval='reset_index', argrepr='reset_index', offset=896, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=45, argval=True, argrepr='True', offset=898, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=46, argval=('drop',), argrepr="('drop',)", offset=900, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION_KW', opcode=141, arg=1, argval=1, argrepr='', offset=902, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=58, argval='dataframes', argrepr='dataframes', offset=904, starts_line=None, is_jump_target=False)
Instruction(opname='POP_BLOCK', opcode=87, arg=None, argval=None, argrepr='', offset=906, starts_line=None, is_jump_target=False)
Instruction(opname='EXTENDED_ARG', opcode=144, arg=1, argval=1, argrepr='', offset=908, starts_line=None, is_jump_target=False)
Instruction(opname='JUMP_ABSOLUTE', opcode=113, arg=276, argval=552, argrepr='to 552', offset=910, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=912, starts_line=185, is_jump_target=True)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=914, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=916, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=55, argval='driver', argrepr='driver', offset=918, starts_line=186, is_jump_target=False)
Instruction(opname='LOAD_METHOD', opcode=160, arg=56, argval='get', argrepr='get', offset=920, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=29, argval='https://www.masothue.com/', argrepr="'https://www.masothue.com/'", offset=922, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=1, argval=1, argrepr='', offset=924, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=926, starts_line=None, is_jump_target=False)
Instruction(opname='POP_EXCEPT', opcode=89, arg=None, argval=None, argrepr='', offset=928, starts_line=187, is_jump_target=False)
Instruction(opname='EXTENDED_ARG', opcode=144, arg=1, argval=1, argrepr='', offset=930, starts_line=None, is_jump_target=False)
Instruction(opname='JUMP_ABSOLUTE', opcode=113, arg=276, argval=552, argrepr='to 552', offset=932, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=48, argval='data', argrepr='data', offset=934, starts_line=194, is_jump_target=True)
Instruction(opname='LOAD_ATTR', opcode=106, arg=81, argval='merge', argrepr='merge', offset=936, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=58, argval='dataframes', argrepr='dataframes', offset=938, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=47, argval='left', argrepr="'left'", offset=940, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=24, argval='Mã số thuế', argrepr="'Mã số thuế'", offset=942, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=48, argval=('how', 'on'), argrepr="('how', 'on')", offset=944, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION_KW', opcode=141, arg=3, argval=3, argrepr='', offset=946, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=82, argval='DF', argrepr='DF', offset=948, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=49, argval=<code object map_data at 0x000002C9792EEAD0, file "mst_com.py", line 200>, argrepr='<code object map_data at 0x000002C9792EEAD0, file "mst_com.py", line 200>', offset=950, starts_line=200, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=50, argval='map_data', argrepr="'map_data'", offset=952, starts_line=None, is_jump_target=False)
Instruction(opname='MAKE_FUNCTION', opcode=132, arg=0, argval=0, argrepr='', offset=954, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=83, argval='map_data', argrepr='map_data', offset=956, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=82, argval='DF', argrepr='DF', offset=958, starts_line=212, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=42, argval='Mã ngành nghề', argrepr="'Mã ngành nghề'", offset=960, starts_line=None, is_jump_target=False)
Instruction(opname='BINARY_SUBSCR', opcode=25, arg=None, argval=None, argrepr='', offset=962, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_METHOD', opcode=160, arg=84, argval='apply', argrepr='apply', offset=964, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=51, argval=<code object <lambda> at 0x000002C9792EEA20, file "mst_com.py", line 212>, argrepr='<code object <lambda> at 0x000002C9792EEA20, file "mst_com.py", line 212>', offset=966, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=52, argval='<lambda>', argrepr="'<lambda>'", offset=968, starts_line=None, is_jump_target=False)
Instruction(opname='MAKE_FUNCTION', opcode=132, arg=0, argval=0, argrepr='', offset=970, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_METHOD', opcode=161, arg=1, argval=1, argrepr='', offset=972, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=82, argval='DF', argrepr='DF', offset=974, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=53, argval='Mã Ngành nghề TPBank', argrepr="'Mã Ngành nghề TPBank'", offset=976, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=54, argval='Tên ngành nghề TPBank', argrepr="'Tên ngành nghề TPBank'", offset=978, starts_line=None, is_jump_target=False)
Instruction(opname='BUILD_LIST', opcode=103, arg=2, argval=2, argrepr='', offset=980, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_SUBSCR', opcode=60, arg=None, argval=None, argrepr='', offset=982, starts_line=None, is_jump_target=False)
Instruction(opname='BUILD_LIST', opcode=103, arg=0, argval=0, argrepr='', offset=984, starts_line=218, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=55, argval=('STT', 'CIF', 'CusTomer_Name', 'Mã số thuế', 'Mã ngành nghề', 'Tên ngành nghề', 'Mã Ngành nghề TPBank', 'Tên ngành nghề TPBank'), argrepr="('STT', 'CIF', 'CusTomer_Name', 'Mã số thuế', 'Mã ngành nghề', 'Tên ngành nghề', 'Mã Ngành nghề TPBank', 'Tên ngành nghề TPBank')", offset=986, starts_line=None, is_jump_target=False)
Instruction(opname='LIST_EXTEND', opcode=162, arg=1, argval=1, argrepr='', offset=988, starts_line=None, is_jump_target=False)
Instruction(opname='STORE_NAME', opcode=90, arg=85, argval='selected_col', argrepr='selected_col', offset=990, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=82, argval='DF', argrepr='DF', offset=992, starts_line=226, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=85, argval='selected_col', argrepr='selected_col', offset=994, starts_line=None, is_jump_target=False)
Instruction(opname='BINARY_SUBSCR', opcode=25, arg=None, argval=None, argrepr='', offset=996, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_ATTR', opcode=106, arg=86, argval='to_excel', argrepr='to_excel', offset=998, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=56, argval='./Output/Crawl_data_', argrepr="'./Output/Crawl_data_'", offset=1000, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=38, argval='ngay_du_lieu', argrepr='ngay_du_lieu', offset=1002, starts_line=None, is_jump_target=False)
Instruction(opname='FORMAT_VALUE', opcode=155, arg=0, argval=(None, False), argrepr='', offset=1004, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=57, argval='.xlsx', argrepr="'.xlsx'", offset=1006, starts_line=None, is_jump_target=False)
Instruction(opname='BUILD_STRING', opcode=157, arg=3, argval=3, argrepr='', offset=1008, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=58, argval=False, argrepr='False', offset=1010, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=59, argval=('index',), argrepr="('index',)", offset=1012, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION_KW', opcode=141, arg=2, argval=2, argrepr='', offset=1014, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=1016, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=82, argval='DF', argrepr='DF', offset=1018, starts_line=227, is_jump_target=False)
Instruction(opname='LOAD_ATTR', opcode=106, arg=86, argval='to_excel', argrepr='to_excel', offset=1020, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=56, argval='./Output/Crawl_data_', argrepr="'./Output/Crawl_data_'", offset=1022, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=38, argval='ngay_du_lieu', argrepr='ngay_du_lieu', offset=1024, starts_line=None, is_jump_target=False)
Instruction(opname='FORMAT_VALUE', opcode=155, arg=0, argval=(None, False), argrepr='', offset=1026, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=60, argval='_full.xlsx', argrepr="'_full.xlsx'", offset=1028, starts_line=None, is_jump_target=False)
Instruction(opname='BUILD_STRING', opcode=157, arg=3, argval=3, argrepr='', offset=1030, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=58, argval=False, argrepr='False', offset=1032, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=59, argval=('index',), argrepr="('index',)", offset=1034, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION_KW', opcode=141, arg=2, argval=2, argrepr='', offset=1036, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=1038, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_NAME', opcode=101, arg=50, argval='print', argrepr='print', offset=1040, starts_line=228, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=61, argval='Hoàn tất =========================', argrepr="'Hoàn tất ========================='", offset=1042, starts_line=None, is_jump_target=False)
Instruction(opname='CALL_FUNCTION', opcode=131, arg=1, argval=1, argrepr='', offset=1044, starts_line=None, is_jump_target=False)
Instruction(opname='POP_TOP', opcode=1, arg=None, argval=None, argrepr='', offset=1046, starts_line=None, is_jump_target=False)
Instruction(opname='LOAD_CONST', opcode=100, arg=1, argval=None, argrepr='None', offset=1048, starts_line=None, is_jump_target=False)
Instruction(opname='RETURN_VALUE', opcode=83, arg=None, argval=None, argrepr='', offset=1050, starts_line=None, is_jump_target=False)

# =====================================================
# CONSTANTS IN CODE
# =====================================================

# CONST[0]: 0
# CONST[11]: 'ignore'
# CONST[13]: '<style>.container { width:90% !important; }</style>'
# CONST[14]: '%d-%m-%Y'
# CONST[15]: 'Tham chiếu/'
# CONST[16]: '\\MapnganhKT_theo nganh SBV TPBank_Cap04.xlsx'
# CONST[17]: 'str'
# CONST[19]: 'Input\\Chưa xử lý'
# CONST[20]: 'Input\\Đã xử lý'
# CONST[21]: <code object>
# CONST[22]: '<listcomp>'
# CONST[23]: '\\'
# CONST[24]: 'Mã số thuế'
# CONST[25]: 'Đang sử lý ================================'
# CONST[26]: 'Không tìm thấy cột mã số thuế ============='
# CONST[27]: 'Xử lý file lỗi =============================='
# CONST[28]: 'Số mã số thuế: '
# CONST[29]: 'https://www.masothue.com/'
# CONST[30]: 2
# CONST[31]: 10
# CONST[32]: 14
# CONST[33]: ' sai định dạng'
# CONST[34]: 'input-group'
# CONST[35]: 'q'
# CONST[36]: 3
# CONST[37]: '//table[@class="table-taxinfo"]/tbody/tr'
# CONST[38]: 'td'
# CONST[39]: 1
# CONST[40]: '//table[@class="table"]/tbody/tr'
# CONST[41]: '//td/strong'
# CONST[42]: 'Mã ngành nghề'
# CONST[43]: 'Tên ngành nghề'
# CONST[45]: True
# CONST[47]: 'left'
# CONST[49]: <code object>
# CONST[50]: 'map_data'
# CONST[51]: <code object>
# CONST[52]: '<lambda>'
# CONST[53]: 'Mã Ngành nghề TPBank'
# CONST[54]: 'Tên ngành nghề TPBank'
# CONST[56]: './Output/Crawl_data_'
# CONST[57]: '.xlsx'
# CONST[58]: False
# CONST[60]: '_full.xlsx'
# CONST[61]: 'Hoàn tất ========================='
